_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://docker.for.mac.localhost:8080
    routes:
      - name: auth-route
        paths:
          - /api/v1/members
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        protocols:
          - http